### ISSUE TITLE
How to make an incremental full disk backup?

### ISSUE THREAD

**Issue by eggbean** [DonyorM/weresync#29]
Just to make it easier to get started with this, how do I make an incremental full disk backup of a running live disk, with no deduplication, so that the backup disk can replace the source disk in the case of failure? I want to set a cron job so that it keeps the backup disk incrementally updated once a day. Thanks.

**Comment by DonyorM** [comment]
In order to set this up with a cron job you'll want to use [the command line interface](https://weresync.readthedocs.io/en/master/weresync.html).

The basic process is as follows.

1. Start the daemon with `sudo weresync-daemon > /dev/null 2>&1 &` (you may want to redirect the output to a log somewhere)
2. Run `weresync /dev/sda /dev/sdb`

Before you run the cron job the first time you should probably run weresync with the `-C` flag so it can setup the partitions. I would just do this manually. 

`weresync -C /dev/sda /dev/sdb`

Depending on your exact setup you may need other options. Watch the output of the -C command to see if it comes up with errors. Are you using a UEFI based bootloader?

**Comment by DonyorM** [comment]
Closing this since I believe the question is answered. Feel free to re-open if you have more questions.
